[package]
name = "server"
version = "0.1.0"
authors = ["ajuvercr <arthur.vercruysse@ugent.be>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

tokio-core = "0.1.17"
tokio-io = "0.1"
tokio = "0.1.5"
futures = "0.1.21"